code_to_ru_text = {
	'A001': 'Имя {0} уже используется в python. Назовите как-нибудь по-другому или добавьте "_" в конец',
	'A002': 'Имя {0} уже используется в python. Назовите как-нибудь по-другому или добавьте "_" в конец',
	'A003': 'Имя {0} уже используется в python. Назовите как-нибудь по-другому или добавьте "_" в конец',
	'C901': 'Цикломатическая сложность функции {0} слишком велика: {1}. Разбейте её на подфункции, сделайте логику более линейной.',
	'E101': 'Отступ содержит и пробелы, и табуляции. Замените всё на пробелы.',
	'E111': 'Величина отступа должна делиться на 4',
	'E112': 'Здесь должен быть сдвинутый блок',
	'E113': 'Здесь не может быть такого отступа',
	'E114': 'Величина отступа должна делиться на 4, а не делится: {0}',
	'E115': 'Здесь должен быть сдвинутый блок {0}',
	'E116': 'Здесь не может быть такого отступа {0}',
	'E121': 'Строчка продолжает предыдущую со слишком маленьким отступом. Сделайте хотя бы 4.',
	'E122': 'Строчка продолжает предыдущую без отступа. Сделайте хотя бы 4.',
	'E123': "Закрывающая скобка в таком контексте должна стоять на том же уровне, что и начало строчки, в которой эта скобка открыта",
	'E124': 'Закрывающая скобка в таком контексте должна стоять на том же уровне, что и её открывающая',
	'E126': 'continuation line over-indented for hanging indent',
	'E127': 'continuation line over-indented for visual indent',
	'E128': 'continuation line under-indented for visual indent',
	'E129': 'visually indented line with same indent as next logical line',
	'E131': 'continuation line unaligned for hanging indent',
	'E201': 'Удалите пробел после {0}',
	'E202': 'Удалите пробел перед {0}',
	'E203': 'Удалите пробел перед {0}',
	'E211': 'Удалите пробел перед {0}',
	'E221': 'Тут больше 1 пробела, оставьте ровно 1',
	'E222': 'Тут больше 1 пробела, оставьте ровно 1',
	'E225': 'Поставьте пробелы вокруг оператора',
	'E226': 'Поставьте пробелы вокруг арифметического оператора',
	'E227': 'missing whitespace around bitwise or shift operator',
	'E228': 'missing whitespace around modulo operator',
	'E231': 'Добавьте пробел после {0}',
	'E241': 'Тут после {0} больше 1 пробела, оставьте ровно 1',
	'E251': 'В параметрах знак «=» пробелами не отделяется, удалите пробелы',
	'E261': 'Перед строчным комментарием поставьте 2 пробела',
	'E262': 'Строчный комментарий должен начинаться с {0}',
	'E265': 'Блочный комментарий должен начинаться с {0}',
	'E266': 'too many leading {0} for block comment',
	'E271': 'multiple spaces after keyword',
	'E272': 'multiple spaces before keyword',
	'E275': 'missing whitespace after keyword',
	'E301': 'expected 1 blank line, found {0}',
	'E302': 'expected 2 blank lines, found {0}',
	'E303': 'too many blank lines {0}',
	'E304': 'blank lines found after function decorator',
	'E305': 'expected 2 blank lines after class or function definition, found {0}',
	'E306': 'expected 1 blank line before a nested definition, found {0}',
	'E401': 'multiple imports on one line',
	'E402': 'module level import not at top of file',
	'E501': 'line too long {0}',
	'E502': 'the backslash is redundant between brackets',
	'E701': 'multiple statements on one line {0}',
	'E702': 'multiple statements on one line {0}',
	'E703': 'statement ends with a semicolon',
	'E704': 'multiple statements on one line {0}',
	'E711': 'comparison to None should be {0}',
	'E712': 'comparison to {2} should be {0} or {1}',
	'E713': 'test for membership should be {0}',
	'E714': 'test for object identity should be {0}',
	'E721': 'do not compare types, use {0}{1}',
	'E722': "do not use bare except'",
	'E731': 'do not assign a lambda expression, use a def',
	'E741': 'ambiguous variable name {0}',
	'E743': 'ambiguous function definition {0}',
	'F401': '{0} imported but unused',
	'F403': '{0} used; unable to detect undefined names',
	'F405': '{0} may be undefined, or defined from star imports: {1}',
	'F406': '{0} only allowed at module level',
	'F601': 'dictionary key {0} repeated with different values',
	'F701': '{0} outside loop',
	'F706': '{0} outside function',
	'F811': 'redefinition of unused {0} from line {1}',
	'F821': 'undefined name {0}',
	'F823': 'local variable {0} {1} referenced before assignment',
	'F841': 'local variable {0} is assigned to but never used',
	'W191': 'indentation contains tabs',
	'W291': 'trailing whitespace',
	'W292': 'no newline at end of file',
	'W293': 'blank line contains whitespace',
	'W391': 'blank line at end of file',
	'W503': 'line break before binary operator',
}

text_to_ru_text = {
    "IndentationError: unindent does not match any outer indentation level": '',
    "TokenError: EOF in multi-line statement": '',
    "SyntaxError: can't assign to comparison": '',
    "SyntaxError: can't assign to function call": '',
    "SyntaxError: can't assign to operator": '',
    "SyntaxError: keyword can't be an expression": '',
    "IndentationError: expected an indented block": '',
    "IndentationError: unexpected indent": '',
    "SyntaxError: EOL while scanning string literal": '',
    "SyntaxError: invalid character in identifier": '',
    "SyntaxError: invalid syntax": '',
    "SyntaxError: invalid token": '',
    "SyntaxError: positional argument follows keyword argument": '',
    "SyntaxError: unexpected character after line continuation character": '',
    "SyntaxError: unexpected EOF while parsing": '',
}
